// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urcsbhdturxsvwksjdru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyY3NiaGR0dXJ4c3Z3a3NqZHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTIyMTAsImV4cCI6MjA2NjE2ODIxMH0.VVRs7tFU1kpOIMpEV0oItKtre9l-fl-EfsjV0ivsgyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);